name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      # with:
      #   cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Install GCloud
      run: sudo snap install google-cloud-cli --classic

    - name: Setup GCP
      run: gcloud config set auth/impersonate_service_account sa-terraform-org@prj-b-seed-3d8e.iam.gserviceaccount.com

    - name: Terraform init
      run: |
        export GOOGLE_IMPERSONATE_SERVICE_ACCOUNT="sa-terraform-org@prj-b-seed-3d8e.iam.gserviceaccount.com"
        terraform init -chdir="./1-org/envs/shared/"
        terraform plan -chdir="./1-org/envs/shared/"
